### ISSUE TITLE
2.3.5 Causes Fatal Error

### ISSUE THREAD

**Issue by jcatello** [wp-media/rocket-lazy-load#127]
`Fatal error: Uncaught Error: Class 'RocketLazyLoadPlugin\Plugin' not found in /home/nginx/domains/domain.com/public/wp-content/plugins/rocket-lazy-load/main.php:9
`

**Comment by DahmaniAdame** [comment]
@jcatello The issue is fixed on version `2.3.6`.

It's already available on the official WordPress repository.

Sorry for the trouble :)

Related - https://secure.helpscout.net/conversation/1863694993/339939/
