### ISSUE TITLE
Does not work in IE 10 because of dataset usage

### ISSUE THREAD

**Issue by bonny** [wp-media/rocket-lazy-load#17]
Using this plugin in IE 10 gave som errors due to the use of dataset, for example `Unable to get property 'wasProcessed' of undefined or null reference lazyload-8.0.3.js`.

According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset dataset is available in IE 11 and above.

By using this dataset shim I was able to make the lazy loading work:
https://gist.github.com/brettz9/4093766

I think a mention about this in the readme would be nice, and maybe also a mention about the shim to help people debug any IE issues.

(I read on http://docs.wp-rocket.me/article/278-common-issues-with-lazyload
that the plugin should work on IE 9 and above, but maybe that doc is for the bigger wp rocket plugin.)

**Comment by Tabrisrp** [comment]
Indeed the current version of the lazyload script we use is not compatible with IE9/10, but a more recent version is available so I can update the plugin to it to restore compatibility.

The WP Rocket documentation is for WP Rocket plugin only, and the lazyload in it is different from the one here.

Thank you for reporting.
