### ISSUE TITLE
Conflict with MasterSlider

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/rocket-lazy-load#36]
The first few slides load correctly, but after the 2nd or 3rd, they become blank.
This did not happen with the previous version of lazyload.
https://secure.helpscout.net/conversation/490146023/55938?folderId=377611

**Comment by Tabrisrp** [comment]
Do we have masterSlider on one of our testing websites?

**Comment by webtrainingwheels** [comment]
Nope.
