### ISSUE TITLE
404 error in IE

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/rocket-lazy-load#40]
When LazyLoad is active in IE it generates an additional request which is seen as "pending" in the browser, and can be reported as a 404 by logging tools. This request isn't present in Chrome and FF.
LazyLoad itself seems to still work.

IE 11:
![ie_11](https://user-images.githubusercontent.com/1043076/34425697-4caecf86-ebe3-11e7-9495-d3b0fb8d59aa.jpg)
https://www.webpagetest.org/result/171228_8A_35db68854400ac37eb4ade413f8a3666/1/details/#step1_request11

IE 16 / Edge:
![ll_ie_404](https://user-images.githubusercontent.com/1043076/34425707-6680f59c-ebe3-11e7-9bcc-8e08dbd19ff5.jpg)

example ticket: 
https://secure.helpscout.net/conversation/491305864/56100/?folderId=273764

**Comment by Tabrisrp** [comment]
That should be fixed with the new way to load the lazyload script
