### ISSUE TITLE
Does not seem to be working with images included with wp_get_attachment_image

### ISSUE THREAD

**Issue by thomasmery** [wp-media/rocket-lazy-load#42]
Hi there,

Thanks for the plugin! much appreciated :)

so I was testing the plugin and noticed that images that were added using `wp_get_attachment_image` would not be lazy loaded

seems like this is because the filtering of the img tags to add the `data-*` attributes is not possible  for `wp_get_attachment_image` because of the way _rocket-lazy-load_ operates, using `preg_replace_callback` to alter img tags (as there is no filter available on the html outputs of the method)

a discussion on the lack of filter for the html output of `wp_get_attachment_image` is here: https://core.trac.wordpress.org/ticket/27399 (you're probably aware of it)

the filter might be added to core in the future but another recommandation would be to use `wp_get_attachment_image_attributes` filter for this case

I'm reaching out because I'd like to know if you agree with what I describe and if a workaround or solution is available - or in the works - or if you'd be ready to accept a PR if I had time to work on something to solve the issue on my end.

I could use the plugin method directly on the code that outputs the image like: 

`<?php echo rocket_lazyload_images(wp_get_attachment_image( $image['id'], 'thumbnail', false)); ?>`

but this is not very convenient and future proof

thanks in advance for any input ton this

**Comment by lkraav** [comment]
For silencing WooCommerce PHP notices due to this issue, `remove_filter( 'wp_get_attachment_image_attributes', 'wc_get_attachment_image_attributes' );` seems to do the trick.

**Comment by lkraav** [comment]
Has this been officially solved? I've seen issues left open before, even though minor releases have patched things up.

**Comment by Tabrisrp** [comment]
I fixed the WooCommerce PHP notice in the latest minor version.

As for the global `wp_get_attachment_image` compatibility, lazyload is applied on it now, without the `noscript` fallback

**Comment by mdmoreau** [comment]
@Tabrisrp Do you know when/if ```wp_get_attachment_image``` support will come to the lazy loading feature within WP Rocket? Ended up using this plugin alongside WP Rocket just for that one feature, so I was curious if there are plans to include it at some point. Thanks!

**Comment by Tabrisrp** [comment]
The enhancements done on version 2.0 of this plugin will be merged in the next major version of WP Rocket too.
