### ISSUE TITLE
Setting data-no-lazy to 1 on images does not work since 1.4.8

### ISSUE THREAD

**Issue by janvitos** [wp-media/rocket-lazy-load#59]
Hi,

I noticed setting data-no-lazy to 1 on images does not work anymore in version 1.4.8. The plugin still lazy loads the images that have the flag set while it should skip them.

Thanks.

**Comment by janvitos** [comment]
Any update on this?

**Comment by Tabrisrp** [comment]
The image might have the class `lazyloaded` added to it, but it doesn't mean it has been.

Is there a `data-lazy-src` attribute, and a `noscript` tag following the image? If not, it means the exclusion works correctly

**Comment by notatamas** [comment]
I can confirm that this issue is not fixed yet.

**Comment by janvitos** [comment]
You can temporarily fix this problem while they work on the issue by adding this line to your functions.php file:

`remove_filter( 'wp_get_attachment_image_attributes', 'rocket_lazyload_get_attachment_image', 11 );`

I'm not sure what impact this might have on other features of the plugin, so be careful. But it had none for me whatsoever and it made **data-no-lazy** work again.

**Comment by janvitos** [comment]
Fixed in new version.
