### ISSUE TITLE
How can I make this work with background images?

### ISSUE THREAD

**Issue by notatamas** [wp-media/rocket-lazy-load#65]
The dependency of this plugin works with background images as well.
I tried data-lazy-src and data-bg-src but none of them worked.

**Comment by Tabrisrp** [comment]
For now it's not supported in the plugin. We could add a first step with a filter on the elements, so you can set your own class to detect a div with a background image.

**Comment by Tabrisrp** [comment]
With version 2.0

The element you want to apply lazyload on must have this specific markup:

`<div class="rocket-lazyload-bg" data-bg="url(../img/image.jpg)"></div>`

The element must have the class `rocket-lazyload-bg`, and a `data-bg` attribute, which value is the CSS url for the image.
