### ISSUE TITLE
New rocket_lazyload_get_attachment_image function broke the plugin

### ISSUE THREAD

**Issue by janvitos** [wp-media/rocket-lazy-load#71]
Hi,

So I opened two (2) tickets (#60 and #59) regarding issues with with this plugin, but they're still not fixed after a few months.

Anyways, I figured out what broke the plugin, and it's the new rocket_lazyload_get_attachment_image function that was added in 1.4.8. Removing this function fixes the problems for ticket #59.

I didn't dig any further to find out why this specific function breaks the plugin, but for anyone having the issue mentioned in ticket #59 and who's interested in getting this plugin working properly again, then you just have to add this line to your functions.php file:

`remove_filter( 'wp_get_attachment_image_attributes', 'rocket_lazyload_get_attachment_image', 11 );`

Hopefully this problem will be resolved in the next version.

**Comment by Tabrisrp** [comment]
The 2.0 version removed this function and use a new way to apply lazyload. I suggest to try it and see if things now work correctly.

**Comment by janvitos** [comment]
@Tabrisrp, I will try that, thank you.

**Comment by janvitos** [comment]
Fixed in new version.
