### ISSUE TITLE
construct() error - new update broke whole site

### ISSUE THREAD

**Issue by KukyMan** [wp-media/rocket-lazy-load#73]
So i updated and after activation, every page on the web shows only this error.

> Catchable fatal error: Argument 3 passed to RocketLazyLoadPlugin\Subscriber\LazyloadSubscriber::__construct() must be an instance of RocketLazyload\Image, string given in /var/www/clients/client17/web218/web/wp-content/plugins/rocket-lazy-load/src/Subscriber/LazyloadSubscriber.php on line 71

**Comment by Tabrisrp** [comment]
should be fixed with 2.0.2
