### ISSUE TITLE
SVG placeholder broken and throws "Bad value" error in the W3C html validator

### ISSUE THREAD

**Issue by janvitos** [wp-media/rocket-lazy-load#82]
Hi,

The new SVG placeholder is not working properly and the SVG is not being loaded. It shows a broken image icon before the image is lazy loaded and throws the following error in the W3C html validator (https://validator.w3.org/):

`Bad value data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 1 1\'%3E%3C/svg%3E for attribute src on element img: Illegal character in scheme data: space is not allowed.`

To fix it, I added this code in my theme's functions.php file:

```
function change_rocket_lazyload_placeholder() {
	return "data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%201%201'%3E%3C/svg%3E";
}
add_filter('rocket_lazyload_placeholder', 'change_rocket_lazyload_placeholder');
```

This loads the SVG properly without the broken image icon and passes the W3C html validation test.

**Comment by Tabrisrp** [comment]
Yes, I'm going to fix this in the next version
