### ISSUE TITLE
Lazy Load Background Images With LI

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/rocket-lazy-load#93]
There are many scenarios where a user might be using an '`<li>'` for a list and attaching a background image to the list. There should be a way to automatically handle the lazy loading much like how you can with `<div>` elements.

**Comment by Tabrisrp** [comment]
Is it a `<li>` with a style attribute to it?

`<li style="background-image:url(image.png)">`

**Comment by ScottTravisHartley** [comment]
Yes, exactly like that the current code only checks for the <div style if it could check for other elements like <li> it would expand it's use cases.
