### ISSUE TITLE
Placeholder size

### ISSUE THREAD

**Issue by MDSilviu** [wp-media/rocket-lazy-load#95]
The actual svg placeholder used it's causing problems, since the viewbox it's a square and makes the browser reserve a square for space and for images that have random sizes this doesn't play well. For example i have problem with parallax at the top of a page since they fire before the lazyload gets the image and they calculate their passion using the square placeholder.
From what i've seen in the code this could a be an easy fix and just pass to the placeholder the width and the height of the image and this way the browser will reserve the correct space for the image that will be loaded and the page won't jump around when the image with it's true height will be loaded and it's not a square

**Comment by Tabrisrp** [comment]
Hi,

This was added in version 2.2 of the plugin, that we just released.
